spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/woowa-chess
    username: woowa-chess
    password: 1234
    schema: classpath*:schema.sql
    initialization-mode: always
#  h2:
#    console:
#      enabled: true
server:
  servlet:
    session:
      timeout: 600